In [1]:
#pandas-panel data lib

In [2]:
#series-basic builiding block of pandas
#holds array of info organized by index
import numpy as np
import pandas as pd

In [3]:
labels=['a','b','c']
myls=[10,20,30]
arr=np.array(myls)
d={'a':10,'b':20,'c':30}

In [5]:
pd.Series(data=myls)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int32

In [9]:
pd.Series(data=[10,'a',4.4])

0     10
1      a
2    4.4
dtype: object

In [17]:
ser1=pd.Series(data=[1,2,3,4],index=['USA','ger','japan','toki'])

In [18]:
ser

USA      1
INDIA    2
japan    3
toki     4
dtype: int64

In [19]:
ser['USA']

1

In [20]:
ser2=pd.Series(data=[1,2,9,4],index=['USA','INDIA','japan','toki'])

In [22]:
ser2

USA      1
INDIA    2
japan    9
toki     4
dtype: int64

In [23]:
ser1+ser2

INDIA     NaN
USA       2.0
ger       NaN
japan    12.0
toki      8.0
dtype: float64

In [24]:
#dataframe
#combination of series share the same index
#data storage format
#multiple column


In [26]:
from numpy.random import randn
np.random.seed(101)
rand_arr=randn(5,4)
rand_arr

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [35]:
df=pd.DataFrame(data=rand_arr,index='a b c d e'.split(),columns='w x y z'.split())
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [38]:
#columns
df['w']

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [39]:
myls=['w','y']
df[myls]

w         y
a  2.706850  0.907969
b  0.651118 -0.848077
c -2.018168  0.528813
d  0.188695 -0.933237
e  0.190794  2.605967

In [40]:

df[['w','y']]

w         y
a  2.706850  0.907969
b  0.651118 -0.848077
c -2.018168  0.528813
d  0.188695 -0.933237
e  0.190794  2.605967

In [42]:
df.w

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [53]:
#new column
df['NEW']=df['w']+df['y']

In [54]:
df

w         x         y         z       new       NEW
a  2.706850  0.628133  0.907969  0.503826  3.614819  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762  2.796762

In [55]:
#remove column
df.drop('NEW',axis=1,inplace=True)

In [60]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [61]:
#rows
df.drop('c')

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [62]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [63]:
#selecting rows
df.loc['a']

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64

In [65]:
df.iloc[2]

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: c, dtype: float64

In [66]:
df.loc[['a','c']]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001

In [68]:
#combine of row and columns
df.loc[['b','c'],['y','z']]

y         z
b -0.848077  0.605965
c  0.528813 -0.589001

In [69]:
#condition and slection
df>0

w      x      y      z
a   True   True   True   True
b   True  False  False   True
c  False   True   True  False
d   True  False  False   True
e   True   True   True   True

In [70]:
df_bool=df>0

In [71]:
df[df_bool]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [72]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [75]:
#based on the condition of one column
df[df['w']>0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [77]:
#codn with specifies row location
df[df['w']>0]['y'].loc['a']

0.9079694464765431

In [78]:
#two codn
codn1=df['w']>0
codn2=df['y']>1

In [79]:
df[(codn1) & (codn2)]

w         x         y         z
e  0.190794  1.978757  2.605967  0.683509

In [80]:
df[(df['w']>0) & (df['y']>1)]

w         x         y         z
e  0.190794  1.978757  2.605967  0.683509

In [81]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [82]:
df.reset_index()

index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [83]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [87]:
#add a new column
new_ind='ca ny nd ms yp'.split()
new_ind

['ca', 'ny', 'nd', 'ms', 'yp']

In [88]:
df['states']=new_ind

In [89]:
df

w         x         y         z states
a  2.706850  0.628133  0.907969  0.503826     ca
b  0.651118 -0.319318 -0.848077  0.605965     ny
c -2.018168  0.740122  0.528813 -0.589001     nd
d  0.188695 -0.758872 -0.933237  0.955057     ms
e  0.190794  1.978757  2.605967  0.683509     yp

In [91]:
df.set_index('states',inplace=True)

In [92]:
df

w         x         y         z
states                                        
ca      2.706850  0.628133  0.907969  0.503826
ny      0.651118 -0.319318 -0.848077  0.605965
nd     -2.018168  0.740122  0.528813 -0.589001
ms      0.188695 -0.758872 -0.933237  0.955057
yp      0.190794  1.978757  2.605967  0.683509

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, ca to yp
Data columns (total 4 columns):
w    5 non-null float64
x    5 non-null float64
y    5 non-null float64
z    5 non-null float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [95]:
df.dtypes

w    float64
x    float64
y    float64
z    float64
dtype: object

In [96]:
df.describe()

w         x         y         z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [97]:
df.corr()

w         x         y         z
w  1.000000 -0.076661  0.039035  0.628925
x -0.076661  1.000000  0.983148 -0.263407
y  0.039035  0.983148  1.000000 -0.131403
z  0.628925 -0.263407 -0.131403  1.000000

In [98]:
df

w         x         y         z
states                                        
ca      2.706850  0.628133  0.907969  0.503826
ny      0.651118 -0.319318 -0.848077  0.605965
nd     -2.018168  0.740122  0.528813 -0.589001
ms      0.188695 -0.758872 -0.933237  0.955057
yp      0.190794  1.978757  2.605967  0.683509

In [101]:
myls='a b c d e'.split()

In [102]:
df['']=myls

In [104]:
df.set_index('',inplace=True)

In [105]:
df

w         x         y         z
                                         
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [106]:
df['w'] >0


a     True
b     True
c    False
d     True
e     True
Name: w, dtype: bool

In [114]:
se1=df['w']>0

In [115]:
se1.value_counts()

True     4
False    1
Name: w, dtype: int64

In [116]:
sum(se1)

4

In [117]:
len(se1)

5

In [131]:
#data i/p o/p
"""csv
json
html
sas
ms exel
sql
google big query..."""
import pandas as pd
import numpy as np

In [133]:
pwd

'C:\\Users\\ASUS\\Desktop\\time series'

In [161]:
arr=np.arange(0,16)
arr=arr.reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [164]:
df=pd.DataFrame(data=arr,columns='a b c d'.split())

In [165]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [166]:
df1=df[['a','b']]

In [168]:
df1.to_csv('new.csv',index=False)

In [169]:
df1.to_excel('new.xlsx',index=False)

In [172]:
df=pd.read_csv('new.csv')
df

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [176]:
df=pd.read_excel('new.xlsx')
df

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [177]:
#myls=pd.read_html('link')
#df=myls[0]
#df

In [178]:
#exercise
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [179]:
df

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [182]:
df.head()

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [183]:
df.columns

Index(['a', 'b'], dtype='object')

In [ ]:
#handing missing value
df.dropna()
df.dropna(axis=1)
df.dropna(thresh=2)
df.fillna(df.mean())#median,most_frequent


In [185]:
#group by op
""".split 
.apply
.cpmbine"""
df

a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [187]:
myls=[1,2,4,9]
myls=np.array(myls)
df['c']=myls

In [188]:
df

a   b  c
0   0   1  1
1   4   5  2
2   8   9  4
3  12  13  9

In [189]:
df.groupby('a').mean()

b  c
a        
0    1  1
4    5  2
8    9  4
12  13  9

In [190]:
df.groupby('a').max()

b  c
a        
0    1  1
4    5  2
8    9  4
12  13  9

In [191]:
df.groupby('a').describe()

b                                             c                     \
   count  mean std   min   25%   50%   75%   max count mean std  min  25%   
a                                                                           
0    1.0   1.0 NaN   1.0   1.0   1.0   1.0   1.0   1.0  1.0 NaN  1.0  1.0   
4    1.0   5.0 NaN   5.0   5.0   5.0   5.0   5.0   1.0  2.0 NaN  2.0  2.0   
8    1.0   9.0 NaN   9.0   9.0   9.0   9.0   9.0   1.0  4.0 NaN  4.0  4.0   
12   1.0  13.0 NaN  13.0  13.0  13.0  13.0  13.0   1.0  9.0 NaN  9.0  9.0   

                   
    50%  75%  max  
a                  
0   1.0  1.0  1.0  
4   2.0  2.0  2.0  
8   4.0  4.0  4.0  
12  9.0  9.0  9.0

In [192]:
df.groupby('a').corr()

b   c
a           
0  b NaN NaN
   c NaN NaN
4  b NaN NaN
   c NaN NaN
8  b NaN NaN
   c NaN NaN
12 b NaN NaN
   c NaN NaN

In [231]:
#common op
df=pd.DataFrame({'col1':[1,2,3,4],'col2':[3,9,7,0],'col3':[7,6,5,4]})

In [232]:
df

col1  col2  col3
0     1     3     7
1     2     9     6
2     3     7     5
3     4     0     4

In [196]:
df['col2'].nunique()

4

In [197]:
df['col2'].unique()

array([3, 9, 7, 0], dtype=int64)

In [198]:
df['col2'].value_counts

<bound method IndexOpsMixin.value_counts of 0    3
1    9
2    7
3    0
Name: col2, dtype: int64>

In [223]:
#col >2 and col2 =4
df1=df[(df['col1']>2) | (df['col2']==7)]

In [227]:
def toto(number):
    return number+2
    

In [228]:
toto(4)

6

In [233]:
df

col1  col2  col3
0     1     3     7
1     2     9     6
2     3     7     5
3     4     0     4

In [235]:
df['col4']=df['col1'].apply(toto)

In [236]:
df

col1  col2  col3  col4
0     1     3     7     3
1     2     9     6     4
2     3     7     5     5
3     4     0     4     6

In [237]:
del df['col4']

In [238]:
df

col1  col2  col3
0     1     3     7
1     2     9     6
2     3     7     5
3     4     0     4

In [ ]:
df.drop()

In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null int64
dtypes: int64(3)
memory usage: 224.0 bytes


In [241]:
df.describe()

col1      col2      col3
count  4.000000  4.000000  4.000000
mean   2.500000  4.750000  5.500000
std    1.290994  4.031129  1.290994
min    1.000000  0.000000  4.000000
25%    1.750000  2.250000  4.750000
50%    2.500000  5.000000  5.500000
75%    3.250000  7.500000  6.250000
max    4.000000  9.000000  7.000000

In [248]:
df.sort_values('col2',ascending=False)

col1  col2  col3
1     2     9     6
2     3     7     5
0     1     3     7
3     4     0     4